### ISSUE TITLE
Format example in README to show bold

### ISSUE THREAD

**Issue by codesections** [rust-clique/man#29]
The example in the README currently shows the output in plain text, when means it cannot show which text is bold.  However, GitHub supports using the `<pre>` tag, which would alow us to use html markup inside the output.  The result would look like this:
<pre>
BASIC(1)                                             General Commands Manual                                             BASIC(1)

<b>NAME</b>
       basic - A basic example

<b>SYNOPSIS</b>
       <b>basic</b> [FLAGS] [OPTIONS]

<b>FLAGS</b>
       <b>-d, --debug</b>
              Enable debug mode

       <b>-v, --verbose</b>
              Enable verbose mode

<b>OPTIONS</b>
       <b>-o, --output=output</b>
              The file path to write output to

<b>USAGE NOTE</b>
       This file will overwrite any file currently stored at the output path.

<b>EXIT STATUS</b>
       <b>0</b>      Successful program execution.

       <b>1</b>      Unsuccessful program execution.

       <b>101</b>    The program panicked.

<b>AUTHORS</b>
         Alice Person &lt;alice@person.com&gt;
         Bob Human &lt;bob@human.com&gt;
</pre>

I think this would be pretty helpful in letting users see the actual formatting that `man` is doing—much of what we're doing is adding bold, so showing the output without that makes the crate look a lot less useful.

My only hesitation about this is crates.io.  Does anyone know if it respects the `<pre>` tag in the same way GitHub does?

**Comment by yoshuawuyts** [comment]
@codesections I think it's fine to try, and see how it turns out tbh. If it renders terribly on crates.io we can always revert. In general very much in favor of this change!
